[package]
name = "this-week-in-past"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
chrono = "0.4"
reqwest = { version = "0.11", features = ["blocking"] }
roxmltree = "0.14"
actix-http = "2"
actix-web = "3"
actix-files = "0.5"
evmap = "10"
clokwerk = "0.3"