name: CI/CD
on:
  push:
  pull_request:
    types:
      - opened
  workflow_dispatch: # allow manual execution

env:
  IMAGE_NAME: rouhim/this-week-in-past
  TAG: latest

jobs:

  check-oci-config:
    name: Check Containerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  check-repo:
    name: Check git repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  check-code-style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v2 # use rust / cargo caching
        with:
          cache-on-failure: "true"

      - name: Check the code style
        run: cargo fmt --all -- --check

  check-code:
    name: Check rust code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v2 # use rust / cargo caching
        with:
          cache-on-failure: "true"

      - name: Verify code
        run: cargo clippy

  test:
    name: Run application tests
    runs-on: ubuntu-latest
    env:
      BIGDATA_CLOUD_API_KEY: ${{ secrets.BIGDATA_CLOUD_API_KEY }}
      OPEN_WEATHER_MAP_API_KEY: ${{ secrets.OPEN_WEATHER_MAP_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v2 # use rust / cargo caching
        with:
          cache-on-failure: "true"

      - name: Test code
        run: cargo test

  check-unused-dependencies:
    name: Check for unused deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      - uses: Swatinem/rust-cache@v2 # use rust / cargo caching
        with:
          cache-on-failure: "true"

      - name: Install cargo-udeps
        run: cargo install cargo-udeps --locked

      - name: Analyze dependencies
        run: cargo +nightly udeps

  build-container-image:
    name: Build container image
    needs: [ check-oci-config, check-repo, check-code-style, check-code, test ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target-platform: [ x86_64-unknown-linux-musl, aarch64-unknown-linux-musl, armv7-unknown-linux-musleabi ]
        include:
          - target-platform: x86_64-unknown-linux-musl
            container-image-arch: linux/amd64
          - target-platform: aarch64-unknown-linux-musl
            container-image-arch: linux/arm64
          - target-platform: armv7-unknown-linux-musleabi
            container-image-arch: linux/arm/v7
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - uses: Swatinem/rust-cache@v2 # use rust / cargo caching
        with:
          cache-on-failure: "true"

      - name: Prepare cross build environment
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build application
        run: cross build --release --target ${{ matrix.target-platform }}

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAG }}
          archs: ${{ matrix.container-image-arch }}
          args: |
            TARGET_PLATFORM=${{ matrix.target-platform }}
          containerfiles: |
            ./Containerfile
          oci: true

      - name: Save container image
        run: podman save -o image.tar ${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Upload container image
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.container-image-arch }}
          path: image.tar

  scan-container-image:
    name: Scan container for vulnerabilities
    needs: build-container-image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container-image-arch: [ linux/amd64, linux/arm64, linux/arm/v7 ]
    steps:
      - name: Download Container Image
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.container-image-arch }}
          path: .

      - name: Restore docker image
        run: docker load --input this-week-in-past.tar

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'rouhim/this-week-in-past:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  test-container-image:
    name: Test container image
    needs: build-container-image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container-image-arch: [ linux/amd64, linux/arm64, linux/arm/v7 ]
    steps:
      - name: Download Container Image
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.container-image-arch }}
          path: .

      - name: Restore docker image
        run: docker load --input this-week-in-past.tar

      - name: Prepare test env
        run: |
          mkdir -p /tmp/test
          wget https://raw.githubusercontent.com/ianare/exif-samples/master/jpg/gps/DSCN0010.jpg -O /tmp/test/DSCN0010.jpg          

      - name: Start test container
        run: podman run -d --name test-container -p 8080:8080 -v /tmp/test:/resources rouhim/this-week-in-past:latest

      - name: Test container web api
        run: wget -q -O /dev/null -t 1 -T 2 http://localhost:8080/api/health

      - name: Cleanup
        run: podman kill test-container && podman rm test-container

  push-container:
    name: Push container image
    needs: [ scan-container-image, test-container-image ]
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' # only push the image if the branch is main
    strategy:
      fail-fast: false
      matrix:
        container-image-arch: [ linux/amd64, linux/arm64, linux/arm/v7 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Container Image
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.container-image-arch }}
          path: .

      - name: Restore container image
        run: podman load --input image.tar

      - name: Push To docker hub
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.TAG }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Update docker hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: rouhim/this-week-in-past